---
apiVersion: v1
kind: Service
metadata:
  name: etcd-client-local
  labels:
    app: etcd
spec:
  ports:
  - port: 2379
    name: client
    protocol: TCP
  clusterIP: None
  selector:
    app: etcd
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-bootstrap-local
  labels:
    app: etcd
data:
  bootstrap.sh: |-
    #!/bin/sh
    while true;
    do
      wget http://localhost:8080/initialization/status -S -O status;
      STATUS=`cat status`;
      case $STATUS in
      "New")
            wget http://localhost:8080/initialization/start -S -O - ;;
      "Progress")
            sleep 1;
            continue;;
      "Failed")
            continue;;
      "Successful")
            exec etcd --data-dir=/var/etcd/data --name=etcd --advertise-client-urls=http://0.0.0.0:2379 --listen-client-urls=http://0.0.0.0:2379 --initial-cluster-state=new --initial-cluster-token=new
            ;;
      esac;
    done
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: etcd-local
spec:
  selector:
    matchLabels:
      app: etcd-local
  serviceName: "etcd-local"
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd-local 
    spec:
      containers:
      - name: etcd
        command:
        - /bootstrap/bootstrap.sh
        image: quay.io/coreos/etcd:v3.3.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -ec
            - ETCDCTL_API=3 etcdctl get foo
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: 2380
          name: server
          protocol: TCP
        - containerPort: 2379
          name: client
          protocol: TCP
        volumeMounts:
        - mountPath: /var/etcd/data
          name: etcd-data-local
        - mountPath: /bootstrap
          name: etcd-bootstrap
      - name: backup
        command:
        - etcdbrctl
        - server
        - --schedule=*/1 * * * *
        - --max-backups=5
        - --data-dir=/var/etcd/data
        - --insecure-transport=true
        - --storage-provider=
        image: eu.gcr.io/gardener-project/gardener/etcdbrctl:0.2.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
        env:
        - name: STORAGE_CONTAINER
          value: etcd-store  # Change the container name here
        volumeMounts:
        - mountPath: /var/etcd/data
          name: etcd-data-local
      volumes:
        - name: etcd-bootstrap
          configMap:
            name: etcd-bootstrap-local
            defaultMode: 0356
  volumeClaimTemplates:
  - metadata:
      name: etcd-data-local
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: 1Gi