{{- if .Values.tls }}
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-etcd-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  ca.crt: {{ .Values.tls.caBundle | b64enc }}
kind: Secret
{{- end }}